// All panel copy, including dynamic status text, lives here. Static labels remain
// in sidepanel.html so Chrome can render the panel before script execution.
/* eslint-disable @typescript-eslint/no-unused-vars -- classic extension scripts share one ordered global scope */
const dynamicCopy = {
  en: {
    noTab: "No active browser tab is available. Open an email and click the Maillume toolbar action again.",
    capturing: "Capturing selected text or the open message...",
    captured: "Selected text captured. Review it before analysis.",
    openMessageCaptured: "Open message captured. Review the subject, sender, and text before analysis.",
    messageChanged: "The webmail page changed. Use the current message before analyzing.",
    captureErrors: { no_active_tab: "No active browser tab is available.", no_selection: "No selection or open Gmail/Outlook message was found. Open a message, optionally select text, and click the Maillume toolbar action again.", multiple_messages: "More than one message is expanded. Select the text you want to check, then click the Maillume toolbar action again.", restricted_page: "Chrome does not allow extensions to read selections on this page. Open the message in a regular webmail tab.", capture_failed: "Chrome could not read the selection from this tab. Reload the message and try the toolbar action again.", handoff_missing: "The one-time capture is no longer available. Open the message and click the Maillume toolbar action again.", handoff_expired: "The one-time capture expired. Open the message and click the Maillume toolbar action again.", panel_unavailable: "Chrome could not open the side panel for this tab. Close other side panels and try again." },
    invalidEndpoint: "Enter an HTTPS deployment URL, or an HTTP localhost URL for local testing.", invalidApiKey: "Enter a valid Maillume API key.", permissionDenied: "Chrome did not grant access to that deployment.", permissionError: "Chrome could not update the deployment permission.", permissionCleanupFailed: "The previous deployment permission could not be removed. The connection was not changed.", saveFailed: "The connection settings could not be saved.",
    connecting: "Waiting for approval in the Maillume account page...", connected: "This browser is connected and ready to analyze messages.", connectionStateConnected: "Connected through your Maillume account.", connectionStateManual: "Connected with an advanced manual API key.", connectionStateDisconnected: "This browser is not connected.", connectButton: "Connect this browser", reconnectButton: "Reconnect this browser", pairingDenied: "The browser connection was denied. No browser credential was created.", pairingExpired: "The browser connection request expired. Start again to create a new request.", pairingFailed: "The browser connection could not be completed. Advanced manual setup is still available.", pairingUnsupported: "This deployment does not support secure browser connection. Open Advanced manual setup to use a key.", updateRequired: "This Maillume extension must be updated before it can connect to this deployment.",
    savedPersistent: "Deployment and API key saved in this Chrome profile for restarts and updates.", savedSession: "Deployment saved. API key kept only for this browser session.", removed: "Browser connection, local credential, and deployment permission removed.", removeStorageFailed: "Chrome could not clear all connection settings. Try removing the connection again.", removePermissionFailed: "The connection and API key were cleared, but Chrome could not remove the deployment permission.", bodyRequired: "Capture or enter the email text first.", connectionRequired: "Connect this browser first, or use Advanced manual setup.", sending: (origin) => `Sending the reviewed text to ${origin}...`, invalidResult: "The deployment returned an invalid analysis response.", incompatibleResult: "The extension and deployment use different analysis versions. Update the extension from the official source, then reload it in chrome://extensions.", authenticationFailed: "The deployment rejected the API key.", browserAuthenticationFailed: "The deployment rejected this browser connection. Reconnect this browser.", quotaExceeded: "This request was limited. Check account usage or wait before trying again.", requestFailed: (status) => `The deployment returned HTTP ${status}.`, unreachable: "The deployment could not be reached. Check the URL and connection permission.", complete: "Assessment complete. Message content and results were not saved by the extension.",
    destination: (endpoint) => `Destination: ${endpoint}`, destinationExpiring: (endpoint, days) => `Destination: ${endpoint}. The API key expires in ${days} day${days === 1 ? "" : "s"}.`, destinationExpired: (endpoint) => `Destination: ${endpoint}. The API key has expired; reconnect this browser.`, browserDestinationExpiring: (endpoint, days) => `Destination: ${endpoint}. This browser connection expires in ${days} day${days === 1 ? "" : "s"} unless it is used.`, browserDestinationExpired: (endpoint) => `Destination: ${endpoint}. This browser connection has expired; reconnect this browser.`, destinationNeedsKey: (endpoint) => `Destination: ${endpoint}. Enter and save an API key.`, unsavedDestination: (endpoint) => `Unsaved destination: ${endpoint}`, unsavedKey: (endpoint) => `Destination: ${endpoint}. The edited API key has not been saved for this session.`, configureDestination: "Destination: configure a Maillume deployment", initializationFailed: "The side panel could not initialize. Close it and use the toolbar action again.",
    levels: { low: "Low", medium: "Medium", high: "High" }, classifications: { likely_phishing: "Likely phishing or fraud", likely_spam: "Likely spam", likely_legitimate: "Likely legitimate", uncertain: "Uncertain" }, coverageComplete: "Maillume received the main message evidence needed for this assessment.", coverageLimited: "Some message evidence was unavailable. Missing details can change the assessment.", coveragePartial: "This assessment uses selected or incomplete text. Content outside the captured text can change the result.", coverageOcr: "This assessment uses OCR-extracted text. Missed text and hidden link destinations can change the result.", coverageLabels: { subject: "Subject", sender: "Sender", fullContent: "Full content", linkDestinations: "Link destinations", authentication: "Authentication results", attachments: "Attachment evidence", extraction: "Text extraction" }, coverageStates: { available: "Available", unavailable: "Unavailable" }, extractionTypes: { direct: "Direct text", ocr: "OCR", parsed: "Parsed .eml" }, points: "points", hideInstructions: "Hide instructions", showInstructions: "Show instructions", showApiKey: "Show API key", hideApiKey: "Hide API key",
  },
  nl: {
    noTab: "Er is geen actief browsertabblad beschikbaar. Open een e-mail en klik opnieuw op de Maillume-knop in de werkbalk.", capturing: "Geselecteerde tekst of het geopende bericht wordt vastgelegd...", captured: "Geselecteerde tekst vastgelegd. Controleer deze voor de analyse.", openMessageCaptured: "Geopend bericht vastgelegd. Controleer onderwerp, afzender en tekst voor de analyse.", messageChanged: "De webmailpagina is gewijzigd. Gebruik het huidige bericht voordat je analyseert.",
    captureErrors: { no_active_tab: "Er is geen actief browsertabblad beschikbaar.", no_selection: "Er is geen geselecteerde tekst gevonden en er kon geen geopend Gmail-/Outlook-bericht worden vastgelegd. Open een bericht, selecteer eventueel tekst en klik opnieuw op de Maillume-knop in de werkbalk.", multiple_messages: "Er zijn meerdere berichten uitgeklapt. Selecteer de tekst die je wilt controleren en klik opnieuw op de Maillume-knop in de werkbalk.", restricted_page: "Chrome staat extensies niet toe selecties op deze pagina te lezen. Open het bericht in een normaal webmailtabblad.", capture_failed: "Chrome kon de selectie uit dit tabblad niet lezen. Laad het bericht opnieuw en probeer de werkbalkknop nogmaals.", handoff_missing: "De eenmalige vastlegging is niet meer beschikbaar. Open het bericht en klik opnieuw op de Maillume-knop in de werkbalk.", handoff_expired: "De eenmalige vastlegging is verlopen. Open het bericht en klik opnieuw op de Maillume-knop in de werkbalk.", panel_unavailable: "Chrome kon het zijpaneel voor dit tabblad niet openen. Sluit andere zijpanelen en probeer het opnieuw." },
    invalidEndpoint: "Voer de HTTPS-URL van een Maillume-omgeving in, of een HTTP-localhost-URL voor lokale tests.", invalidApiKey: "Voer een geldige Maillume API-sleutel in.", permissionDenied: "Chrome heeft geen toegang tot die omgeving verleend.", permissionError: "Chrome kon de toestemming voor deze omgeving niet bijwerken.", permissionCleanupFailed: "De vorige toestemming voor deze omgeving kon niet worden verwijderd. De verbinding is niet gewijzigd.", saveFailed: "De verbindingsinstellingen konden niet worden opgeslagen.", connecting: "Wachten op goedkeuring op de Maillume-accountpagina...", connected: "Deze browser is verbonden en klaar om berichten te analyseren.", connectionStateConnected: "Verbonden via je Maillume-account.", connectionStateManual: "Verbonden met een geavanceerde handmatige API-sleutel.", connectionStateDisconnected: "Deze browser is niet verbonden.", connectButton: "Deze browser verbinden", reconnectButton: "Deze browser opnieuw verbinden", pairingDenied: "De browserverbinding is geweigerd. Er is geen browserreferentie gemaakt.", pairingExpired: "Het verbindingsverzoek is verlopen. Start opnieuw om een nieuw verzoek te maken.", pairingFailed: "De browserverbinding kon niet worden voltooid. Geavanceerde handmatige configuratie blijft beschikbaar.", pairingUnsupported: "Deze omgeving ondersteunt veilig verbinden met de browser niet. Open Geavanceerde handmatige configuratie om een sleutel te gebruiken.", updateRequired: "Deze Maillume-extensie moet worden bijgewerkt voordat ze met deze omgeving kan verbinden.",
    savedPersistent: "Omgeving en API-sleutel opgeslagen in dit Chrome-profiel voor herstarts en updates.", savedSession: "Omgeving opgeslagen. API-sleutel alleen voor deze browsersessie bewaard.", removed: "Browserverbinding, lokale sleutel en toestemming voor deze omgeving verwijderd.", removeStorageFailed: "Chrome kon niet alle verbindingsinstellingen wissen. Probeer de verbinding opnieuw te verwijderen.", removePermissionFailed: "De verbinding en API-sleutel zijn gewist, maar Chrome kon de toestemming voor deze omgeving niet verwijderen.", bodyRequired: "Leg eerst de e-mailtekst vast of voer die in.", connectionRequired: "Verbind eerst deze browser of gebruik Geavanceerde handmatige configuratie.", sending: (origin) => `De gecontroleerde tekst wordt naar ${origin} verzonden...`, invalidResult: "De Maillume-omgeving gaf een ongeldig analyseresultaat terug.", incompatibleResult: "De extensie en Maillume-omgeving gebruiken verschillende analyseversies. Werk de extensie bij vanuit de officiële broncode en laad haar daarna opnieuw via chrome://extensions.", authenticationFailed: "De Maillume-omgeving heeft de API-sleutel geweigerd.", browserAuthenticationFailed: "De Maillume-omgeving heeft deze browserverbinding geweigerd. Verbind deze browser opnieuw.", quotaExceeded: "Deze aanvraag is beperkt. Controleer het accountgebruik of wacht voordat je het opnieuw probeert.", requestFailed: (status) => `De Maillume-omgeving gaf HTTP ${status} terug.`, unreachable: "De Maillume-omgeving is niet bereikbaar. Controleer de URL en toestemming.", complete: "Beoordeling voltooid. De extensie heeft berichtinhoud en resultaten niet opgeslagen.",
    destination: (endpoint) => `Bestemming: ${endpoint}`, destinationExpiring: (endpoint, days) => `Bestemming: ${endpoint}. De API-sleutel verloopt over ${days} ${days === 1 ? "dag" : "dagen"}.`, destinationExpired: (endpoint) => `Bestemming: ${endpoint}. De API-sleutel is verlopen; verbind deze browser opnieuw.`, browserDestinationExpiring: (endpoint, days) => `Bestemming: ${endpoint}. Deze browserverbinding verloopt over ${days} ${days === 1 ? "dag" : "dagen"} als ze niet wordt gebruikt.`, browserDestinationExpired: (endpoint) => `Bestemming: ${endpoint}. Deze browserverbinding is verlopen; verbind deze browser opnieuw.`, destinationNeedsKey: (endpoint) => `Bestemming: ${endpoint}. Voer een API-sleutel in en sla die op.`, unsavedDestination: (endpoint) => `Niet-opgeslagen bestemming: ${endpoint}`, unsavedKey: (endpoint) => `Bestemming: ${endpoint}. De gewijzigde API-sleutel is nog niet opgeslagen voor deze sessie.`, configureDestination: "Bestemming: configureer een Maillume-omgeving", initializationFailed: "Het zijpaneel kon niet worden gestart. Sluit het en gebruik de werkbalkknop opnieuw.",
    levels: { low: "Laag", medium: "Middel", high: "Hoog" }, classifications: { likely_phishing: "Waarschijnlijk phishing of fraude", likely_spam: "Waarschijnlijk spam", likely_legitimate: "Waarschijnlijk legitiem", uncertain: "Onzeker" }, coverageComplete: "Maillume ontving de belangrijkste berichtgegevens voor deze beoordeling.", coverageLimited: "Sommige berichtgegevens waren niet beschikbaar. Ontbrekende details kunnen de beoordeling veranderen.", coveragePartial: "Deze beoordeling gebruikt geselecteerde of onvolledige tekst. Inhoud buiten de vastgelegde tekst kan de beoordeling veranderen.", coverageOcr: "Deze beoordeling gebruikt tekst uit OCR. Gemiste tekst en verborgen linkbestemmingen kunnen de beoordeling veranderen.", coverageLabels: { subject: "Onderwerp", sender: "Afzender", fullContent: "Volledige inhoud", linkDestinations: "Linkbestemmingen", authentication: "Authenticatieresultaten", attachments: "Bijlagegegevens", extraction: "Tekstextractie" }, coverageStates: { available: "Beschikbaar", unavailable: "Niet beschikbaar" }, extractionTypes: { direct: "Directe tekst", ocr: "OCR", parsed: "Verwerkt .eml-bestand" }, points: "punten", hideInstructions: "Uitleg verbergen", showInstructions: "Uitleg tonen", showApiKey: "API-sleutel tonen", hideApiKey: "API-sleutel verbergen",
  },
};

function getLocale() {
  return chrome.i18n.getUILanguage().toLowerCase().startsWith("nl") ? "nl" : "en";
}

function getDynamicCopy() {
  return dynamicCopy[getLocale()];
}

function localizeUi() {
  const locale = getLocale();
  document.documentElement.lang = locale;
  if (locale === "nl") {
    document.querySelectorAll("[data-nl]").forEach((node) => { node.textContent = node.dataset.nl; });
    document.querySelectorAll("[data-nl-aria-label]").forEach((node) => { node.setAttribute("aria-label", node.dataset.nlAriaLabel); });
  }
}
