import type { MarketingDictionary } from "./marketing-translate";

const nl: MarketingDictionary = {
  "Illuminate suspicious email": "Breng verdachte e-mail aan het licht",
  "Shine a light on suspicious email. Maillume reveals the signals behind a message so you can decide what to trust before you click, reply, or pay.": "Schijn licht op verdachte e-mail. Maillume maakt de signalen achter een bericht zichtbaar, zodat je kunt bepalen wat je vertrouwt voordat je klikt, antwoordt of betaalt.",
  "Check an email": "Controleer een e-mail", "View source": "Bekijk de broncode", "Free heuristic checks. No account required. No scan history.": "Gratis heuristische controles. Geen account nodig. Geen scangeschiedenis.",
  "Files parsed in your browser": "Bestanden verwerkt in je browser", "Evidence, never certainty theater": "Bewijs, nooit schijnzekerheid", "AGPL-3.0 open source": "AGPL-3.0-open-source",
  "A clearer view": "Een helderder beeld", "See what an email is asking you to trust.": "Zie wat een e-mail je vraagt te vertrouwen.",
  "Maillume turns the pressure tactics, mismatched domains, suspicious links, and identity clues in an email into a report a non-technical person can act on.": "Maillume zet drukmiddelen, afwijkende domeinen, verdachte links en identiteitssignalen in een e-mail om in een rapport waar ook niet-technische mensen mee verder kunnen.",
  "Flexible input": "Flexibele invoer", "Bring the email you actually received.": "Gebruik de e-mail die je echt hebt ontvangen.", "Paste the message, extract text from a screenshot, or parse an exported .eml file. The file itself stays in your browser.": "Plak het bericht, haal tekst uit een screenshot of verwerk een geëxporteerd .eml-bestand. Het bestand zelf blijft in je browser.",
  "Explainable output": "Uitlegbare uitkomst", "See the signals, not just a scary label.": "Bekijk de signalen, niet alleen een alarmerend label.", "Maillume shows a risk score, suspicious patterns, detected links, and a practical next action so you can make the final call.": "Maillume toont een risicoscore, verdachte patronen, gevonden links en een praktische vervolgstap, zodat jij de uiteindelijke afweging kunt maken.",
  "No scan history": "Geen scangeschiedenis", "The assessment ends when the request does.": "De beoordeling eindigt zodra het verzoek is afgerond.", "The hosted beta does not save email text, sender details, screenshots, .eml files, links, or completed scan results.": "De gehoste bèta bewaart geen e-mailtekst, afzendergegevens, screenshots, .eml-bestanden, links of voltooide scanresultaten.",
  "What leaves the browser": "Wat de browser verlaat", "Only the text needed for this assessment.": "Alleen de tekst die voor deze beoordeling nodig is.", "Screenshot OCR and .eml parsing happen locally. The normalized text is sent to the analysis route for the current score and is not added to a scan database.": "OCR van screenshots en verwerking van .eml-bestanden gebeuren lokaal. De genormaliseerde tekst wordt voor de actuele score naar de analyseroute gestuurd en niet aan een scandatabase toegevoegd.",
  "Your browser": "Je browser", "Parses files and extracts readable text.": "Verwerkt bestanden en haalt leesbare tekst op.", "Maillume analysis": "Maillume-analyse", "Checks risk patterns and returns structured JSON.": "Controleert risicopatronen en geeft gestructureerde JSON terug.", "Request ends": "Verzoek afgerond", "No email content or result is written to scan history.": "Er wordt geen e-mailinhoud of resultaat in een scangeschiedenis opgeslagen.",
  "Hosted by us": "Door ons gehost", "Use the scanner in seconds.": "Gebruik de scanner binnen enkele seconden.", "The official cloud runs the local heuristic analyzer without a maintainer-funded AI key. Anonymous checks remain the default.": "De officiële cloud gebruikt de lokale heuristische analyse zonder een door de beheerder betaalde AI-sleutel. Anonieme controles blijven de standaard.", "Open Maillume": "Open Maillume",
  "Hosted by you": "Door jou gehost", "Run the complete core yourself.": "Draai zelf de volledige kern.", "Deploy the AGPL application on your infrastructure, keep heuristic mode, or connect your own supported AI provider key.": "Implementeer de AGPL-applicatie op je eigen infrastructuur, behoud de heuristische modus of koppel je eigen ondersteunde AI-providersleutel.", "Explore self-hosting": "Ontdek self-hosting",
  "Incident notes · February 2026": "Incidentnotities · februari 2026", "When phishing moves from email to phone.": "Wanneer phishing van e-mail naar telefoon verschuift.", "The reported Odido attack combined credential phishing, impersonation of internal IT, and fraudulent login approval. See what that sequence teaches us without claiming any single tool can guarantee prevention.": "De gemelde aanval op Odido combineerde phishing naar inloggegevens, imitatie van interne IT en goedkeuring van een frauduleuze login. Bekijk wat die reeks ons leert, zonder te beweren dat één hulpmiddel preventie kan garanderen.", "Read the incident notes": "Lees de incidentnotities",
  "Open development": "Open ontwikkeling", "Inspect the code. Improve the checks. Run your own copy.": "Bekijk de code. Verbeter de controles. Draai je eigen versie.", "Follow on GitHub": "Volg op GitHub",

  "Maillume Platform": "Maillume-platform", "Bring a clear email risk report into the tools people already use.": "Breng een helder e-mailrisicorapport naar de hulpmiddelen die mensen al gebruiken.", "The quota-aware API and integrations for Chrome, Gmail, and Outlook are implemented in source. Production acceptance and marketplace review are still required before public availability.": "De API met quotabewaking en integraties voor Chrome, Gmail en Outlook zijn in de broncode geïmplementeerd. Productieacceptatie en beoordeling door de marktplaatsen zijn nog nodig voordat ze openbaar beschikbaar zijn.", "See what is implemented": "Bekijk wat is geïmplementeerd", "Follow development": "Volg de ontwikkeling",
  "Implemented in source": "Geïmplementeerd in de broncode", "A predictable, quota-aware JSON contract.": "Een voorspelbaar JSON-contract met quotabewaking.", "Integrations post normalized message content to `/api/v1/analyze` with a revocable account key and receive the same structured assessment as the scanner.": "Integraties sturen genormaliseerde berichtinhoud met een intrekbare accountsleutel naar `/api/v1/analyze` en ontvangen dezelfde gestructureerde beoordeling als de scanner.", "Production account, key, revocation, and quota acceptance is still in progress. Do not rely on the official cloud API until that launch gate closes.": "Productieacceptatie voor accounts, sleutels, intrekking en quota loopt nog. Vertrouw nog niet op de officiële cloud-API totdat deze lanceringseis is afgerond.",
  "Strict request size and field validation": "Strikte validatie van verzoekgrootte en velden", "Structured response shared by heuristic and AI modes": "Gestructureerd antwoord voor heuristische en AI-modi", "No-store response headers": "No-store-antwoordheaders", "Automated-assessment disclaimer in every result": "Disclaimer over automatische beoordeling in elk resultaat", "OpenAPI specification": "OpenAPI-specificatie", "authenticated beta": "geverifieerde bèta",
  "Integration principles": "Integratieprincipes", "Convenient without becoming invisible.": "Handig zonder onzichtbaar te worden.", "Every integration analyzes only after a clear user action, requests the smallest practical permission scope, and shows or fixes the exact deployment receiving the content.": "Elke integratie analyseert pas na een duidelijke gebruikersactie, vraagt de kleinst praktische machtiging en toont of bepaalt exact welke implementatie de inhoud ontvangt.",
  "User initiated": "Door gebruiker gestart", "No background mailbox harvesting or silent scanning.": "Geen verzameling uit mailboxen op de achtergrond of stille scans.", "Explicit boundary": "Duidelijke grens", "Users know whether analysis is local, official cloud, or self-hosted.": "Gebruikers weten of de analyse lokaal, in de officiële cloud of self-hosted plaatsvindt.", "Portable contract": "Overdraagbaar contract", "Integrations consume the same structured result shape.": "Integraties gebruiken dezelfde gestructureerde resultaatvorm.",
  "Implemented surfaces": "Geïmplementeerde kanalen", "From endpoint to inbox.": "Van endpoint tot inbox.", "Acceptance pending": "Acceptatie loopt", "Source beta": "Broncode-bèta", "Hosted API access": "Toegang tot gehoste API", "The authenticated key and quota flow is implemented in source; production acceptance is still in progress.": "De geverifieerde sleutel- en quotaworkflow is in de broncode geïmplementeerd; productieacceptatie loopt nog.", "Browser extension": "Browserextensie", "A Manifest V3 side panel that sends only text the user explicitly selects to a chosen deployment.": "Een Manifest V3-zijpaneel dat alleen expliciet geselecteerde tekst naar een gekozen implementatie stuurt.", "Gmail add-on": "Gmail-add-on", "A current-message-only Workspace add-on that reads content after the user presses Analyze.": "Een Workspace-add-on die alleen het huidige bericht leest nadat de gebruiker op Analyseren drukt.", "Outlook add-in": "Outlook-invoegtoepassing", "A ReadItem task pane for the open message, with no read/write mailbox permission or background scan.": "Een ReadItem-taakvenster voor het geopende bericht, zonder lees- of schrijfrechten voor de mailbox en zonder achtergrondscan.", "Build in the open": "Open ontwikkelen", "Integration decisions belong in public issues before they reach an inbox.": "Beslissingen over integraties horen in openbare issues voordat ze een inbox bereiken.", "View the roadmap": "Bekijk de roadmap",

  "Pricing": "Prijzen", "Simple, honest pricing for Maillume Cloud and the open-source self-hosted scanner.": "Eenvoudige, eerlijke prijzen voor Maillume Cloud en de open-source self-hosted scanner.", "The safety workflow stays free.": "De veiligheidscontrole blijft gratis.", "The hosted beta charges nothing for core heuristic checks. A small integration API allowance follows production acceptance; future paid plans may fund managed AI and higher limits without removing the free scanner.": "De gehoste bèta rekent niets voor heuristische basiscontroles. Een klein API-tegoed voor integraties volgt na productieacceptatie; toekomstige betaalde abonnementen kunnen beheerde AI en hogere limieten financieren zonder de gratis scanner te vervangen.",
  "forever": "voor altijd", "A quick second opinion for everyday suspicious email.": "Een snelle second opinion voor alledaagse verdachte e-mail.", "Available in beta": "Beschikbaar als bèta", "No account required": "Geen account nodig", "Heuristic email risk assessment": "Heuristische e-mailrisicobeoordeling", "Paste, screenshot, and .eml inputs": "Invoer via plakken, screenshot en .eml", "English and Dutch interface": "Engelse en Nederlandse interface", "Account API keys after production acceptance": "API-accountsleutels na productieacceptatie",
  "per month target": "beoogd per maand", "Managed convenience for people who want Maillume closer to their inbox.": "Beheerd gemak voor mensen die Maillume dichter bij hun inbox willen.", "Planned, not for sale": "Gepland, niet te koop", "Everything in Cloud Free": "Alles van Cloud Free", "Managed AI allowance with hard limits": "Beheerd AI-tegoed met harde limieten", "Official browser and mail integrations": "Officiële browser- en mailintegraties", "Account preferences": "Accountvoorkeuren", "Priority product support": "Voorrang bij productondersteuning", "Read the roadmap": "Lees de roadmap",
  "Run the complete scanner core on infrastructure you control.": "Draai de volledige scannerkern op infrastructuur die jij beheert.", "Available from source": "Beschikbaar als broncode", "Complete heuristic scanner": "Volledige heuristische scanner", "Bring your own supported AI key": "Gebruik je eigen ondersteunde AI-sleutel", "No fee or limit imposed by Maillume": "Geen kosten of limieten opgelegd door Maillume", "Modify and deploy the source": "Pas de broncode aan en implementeer deze", "Community support through GitHub": "Communityondersteuning via GitHub", "Self-host Maillume": "Host Maillume zelf",
  "About the Plus price:": "Over de Plus-prijs:", "EUR 9 is a planning target, not a launch offer. It will only become a real price after provider costs, privacy terms, quotas, and demand have been verified.": "EUR 9 is een planningsdoel, geen introductieaanbod. Het wordt pas een echte prijs nadat providerkosten, privacyvoorwaarden, quota en vraag zijn gecontroleerd.", "Common questions": "Veelgestelde vragen", "No small print hidden in the score.": "Geen kleine lettertjes verborgen in de score.",
  "Will free scans require an account?": "Vereisen gratis scans een account?", "No. Anonymous heuristic scanning is a permanent product boundary. A Google account may later unlock preferences or paid conveniences, but it is not required for the core check.": "Nee. Anoniem heuristisch scannen blijft een vaste productgrens. Een Google-account kan later voorkeuren of betaalde gemakken ontgrendelen, maar is niet nodig voor de basiscontrole.", "Do paid plans make results more certain?": "Maken betaalde abonnementen resultaten zekerder?", "No. Every mode remains an automated risk assessment and never a guarantee. Paid value must come from managed capacity, integrations, and support rather than inflated certainty claims.": "Nee. Elke modus blijft een automatische risicobeoordeling en nooit een garantie. Betaalde waarde moet komen van beheerde capaciteit, integraties en ondersteuning, niet van overdreven zekerheidsclaims.", "Who pays for AI in a self-hosted deployment?": "Wie betaalt AI bij een self-hosted implementatie?", "The operator supplies and pays for their own provider key. Maillume does not place a maintainer-owned key in the open-source application.": "De beheerder levert en betaalt de eigen providersleutel. Maillume plaatst geen sleutel van de maintainer in de open-source applicatie.", "Can I use the source commercially?": "Mag ik de broncode commercieel gebruiken?", "The code is available under AGPL-3.0-only. Review the license and its network source-availability requirements for your deployment. This page is not legal advice.": "De code is beschikbaar onder AGPL-3.0-only. Bekijk voor je implementatie de licentie en de vereisten voor beschikbaarheid van broncode via een netwerk. Deze pagina is geen juridisch advies.", "Need full infrastructure control?": "Volledige controle over de infrastructuur nodig?", "Compare the self-hosted setup": "Vergelijk de self-hosted opzet", "Want to shape the plans?": "Wil je de plannen mede vormgeven?", "Join the open roadmap": "Doe mee aan de open roadmap",

  "Self-hosted": "Self-hosted", "Run the complete Maillume email risk scanner on infrastructure you control.": "Draai de volledige Maillume-e-mailrisicoscanner op infrastructuur die jij beheert.", "Self-hosted Maillume": "Self-hosted Maillume", "Your infrastructure. Your provider key. The complete scanner core.": "Jouw infrastructuur. Jouw providersleutel. De volledige scannerkern.", "Deploy Maillume for your own users, keep analysis heuristic-only, or connect a supported AI provider without sending that key to a project maintainer.": "Implementeer Maillume voor je eigen gebruikers, houd de analyse uitsluitend heuristisch of koppel een ondersteunde AI-provider zonder die sleutel naar een projectbeheerder te sturen.", "View repository": "Bekijk repository", "Read quickstart": "Lees de snelstart",
  "Data boundary": "Datagrens", "Operate the application in your own environment.": "Beheer de applicatie in je eigen omgeving.", "Bring your key": "Gebruik je eigen sleutel", "Choose a supported AI or compatible endpoint.": "Kies een ondersteunde AI-provider of compatibel endpoint.", "Open source": "Open source", "Inspect and modify the AGPL-3.0 codebase.": "Bekijk en wijzig de AGPL-3.0-codebase.", "Same guardrails": "Dezelfde waarborgen", "Keep no-store responses, limits, and disclaimers.": "Behoud no-store-antwoorden, limieten en disclaimers.",
  "Community quickstart": "Snelstart voor de community", "From clone to local scanner.": "Van kloon naar lokale scanner.", "Heuristic mode needs no AI account. Add a server-side provider configuration only when your deployment needs it.": "Voor de heuristische modus is geen AI-account nodig. Voeg alleen een serverconfiguratie voor een provider toe wanneer je implementatie die nodig heeft.", "Clone the repository and install dependencies.": "Kloon de repository en installeer de afhankelijkheden.", "Copy the environment example and select heuristic or AI mode.": "Kopieer het omgevingsvoorbeeld en kies de heuristische of AI-modus.", "Run the checks, then deploy to your preferred Next.js host.": "Voer de controles uit en implementeer daarna op je gewenste Next.js-host.", "Terminal": "Terminal", "heuristic mode": "heuristische modus", "Public AI deployments also need provider-side budgets and deployment-level abuse controls.": "Openbare AI-implementaties hebben ook providerbudgetten en misbruikbeveiliging op implementatieniveau nodig.",
  "Choose the analysis boundary": "Kies de analysegrens", "Two modes, one result contract.": "Twee modi, één resultaatcontract.", "Mode": "Modus", "External provider": "Externe provider", "Best for": "Geschikt voor", "Heuristic": "Heuristisch", "None": "Geen", "Simple, predictable, zero-provider-cost deployments": "Eenvoudige, voorspelbare implementaties zonder providerkosten", "Your configured provider": "Je geconfigureerde provider", "Operators who accept provider processing and manage their own costs": "Beheerders die providerverwerking accepteren en hun eigen kosten beheren",
  "What the project provides": "Wat het project biedt", "Next.js application and analysis API": "Next.js-applicatie en analyse-API", "Paste, screenshot OCR, and .eml workflows": "Workflows voor plakken, screenshot-OCR en .eml", "Heuristic and provider adapter architecture": "Architectuur voor heuristiek en provideradapters", "Synthetic evaluation fixtures and security checks": "Synthetische evaluatiefixtures en beveiligingscontroles", "Deployment and privacy documentation": "Documentatie over implementatie en privacy", "What the operator owns": "Waar de beheerder verantwoordelijk voor is", "Infrastructure, monitoring, and incident response": "Infrastructuur, monitoring en incidentrespons", "AI provider account, terms, budgets, and retention review": "AI-provideraccount, voorwaarden, budgetten en controle van bewaartermijnen", "User disclosures and legal compliance": "Gebruikersinformatie en wettelijke naleving", "Rate limits and abuse prevention at the edge": "Snelheidslimieten en misbruikpreventie aan de rand", "AGPL source-availability obligations": "AGPL-verplichtingen voor beschikbaarheid van broncode", "Community edition": "Community-editie", "Start with the same scanner core.": "Begin met dezelfde scannerkern.", "Open the repository": "Open de repository",

  "What the Odido phishing incident teaches us": "Wat het phishingincident bij Odido ons leert", "How email phishing, internal IT impersonation, and MFA manipulation can form one attack.": "Hoe e-mailphishing, imitatie van interne IT en MFA-manipulatie samen één aanval kunnen vormen.", "Back to Maillume": "Terug naar Maillume", "A phishing email can be the first step, not the whole attack.": "Een phishingmail kan de eerste stap zijn, niet de hele aanval.", "Reporting about the Odido breach shows how stolen credentials, a convincing phone call, and approval of a fraudulent login can work together.": "Berichtgeving over het datalek bij Odido laat zien hoe gestolen inloggegevens, een overtuigend telefoongesprek en goedkeuring van een frauduleuze login kunnen samenwerken.",
  "What was reported": "Wat er is gemeld", "NOS reported that attackers obtained customer-service employees' passwords through phishing emails. They then called employees while posing as Odido's IT department and persuaded them to approve fraudulent login attempts, bypassing an additional security step. Multiple accounts were reportedly compromised and customer data was then collected automatically.": "NOS meldde dat aanvallers via phishingmails wachtwoorden van klantenservicemedewerkers bemachtigden. Vervolgens belden ze medewerkers terwijl ze zich voordeden als de IT-afdeling van Odido en overtuigden hen frauduleuze inlogpogingen goed te keuren, waardoor een extra beveiligingsstap werd omzeild. Naar verluidt werden meerdere accounts overgenomen en daarna automatisch klantgegevens verzameld.", "Read the original NOS report": "Lees het oorspronkelijke NOS-bericht", "Why layered social engineering works": "Waarom gelaagde social engineering werkt", "Email": "E-mail", "A message creates a believable reason to surrender credentials.": "Een bericht geeft een geloofwaardige reden om inloggegevens af te staan.", "Phone call": "Telefoongesprek", "A second channel and an internal identity create confidence and urgency.": "Een tweede kanaal en een interne identiteit wekken vertrouwen en urgentie.", "Approval": "Goedkeuring", "The victim is guided into approving an action they did not initiate.": "Het slachtoffer wordt ertoe gebracht een actie goed te keuren die het niet zelf heeft gestart.",
  "A practical pause": "Een praktische pauze", "Treat unexpected requests for passwords, login approvals, payments, or sensitive information as a reason to stop. Contact the organization through a known number or internal channel, independently verify the request, and never approve an MFA prompt you did not initiate.": "Zie onverwachte verzoeken om wachtwoorden, inloggoedkeuringen, betalingen of gevoelige informatie als reden om te stoppen. Neem via een bekend nummer of intern kanaal contact op met de organisatie, controleer het verzoek onafhankelijk en keur nooit een MFA-melding goed die je niet zelf hebt gestart.", "Where Maillume fits": "Waar Maillume past", "Maillume can provide a second opinion on the email portion and make suspicious signals easier to see. It cannot verify a caller's identity, inspect an organization's internal systems, or guarantee that an email is safe. It should be one part of a broader verification process.": "Maillume kan een second opinion geven over het e-mailgedeelte en verdachte signalen zichtbaarder maken. Het kan de identiteit van een beller niet verifiëren, de interne systemen van een organisatie niet onderzoeken en niet garanderen dat een e-mail veilig is. Het hoort onderdeel te zijn van een breder verificatieproces.", "Remember": "Onthoud", "Use a known contact channel.": "Gebruik een bekend contactkanaal.", "Do not share passwords by email or phone.": "Deel geen wachtwoorden via e-mail of telefoon.", "Reject unexpected login approvals.": "Weiger onverwachte inloggoedkeuringen.", "Report the attempt internally.": "Meld de poging intern.",
};

export const homeNl = nl;
export const platformNl = nl;
export const pricingNl = nl;
export const selfHostedNl = nl;
export const incidentNl = nl;
